openapi: "3.0.0"
info:
  title: User Management Service
  version: 1.0.0
paths:
  /user:
    get:
      summary: Get user information
      description: Get user information
      tags:
        - user
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "cnb"
                  age:
                    type: integer
                    example: 29
                  company:
                    type: string
                    example: "Mat logic"
                  occupation:
                    type: string
                    example: "Lawyer"
      deprecated: false
      security: []
